name: Diagnostics 3
on:
  workflow_dispatch:

jobs:
  diagnose:
    runs-on: ubuntu-latest
    steps:
      - name: Run Diagnostics on EC2
        uses: appleboy/ssh-action@master
        with:
          host: 13.206.145.98
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            head -n 20 /home/ec2-user/Form20-backlog-tracker/app.py
            ls -l /home/ec2-user/Form20-backlog-tracker/app.py
